#!/usr/bin/env bash
set -euo pipefail

# claude-approve installer
# Sets up Discord bot config and adds hooks to Claude Code settings.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="$HOME/.config/claude-approve"
CONFIG_FILE="$CONFIG_DIR/config"
SETTINGS_FILE="$HOME/.claude/settings.json"

echo "=== claude-approve setup ==="
echo ""

# Check dependencies
for cmd in jq curl; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "Error: '$cmd' is required but not installed." >&2
    echo "  brew install $cmd  (macOS)" >&2
    echo "  apt install $cmd   (Linux)" >&2
    exit 1
  fi
done

echo "You'll need a Discord bot. Here's how to set one up (takes ~2 min):"
echo ""
echo "  1. Go to https://discord.com/developers/applications"
echo "  2. Click 'New Application', give it a name, click Create"
echo "  3. Go to 'Bot' in the sidebar"
echo "  4. Click 'Reset Token' and copy the token"
echo "  5. Under 'Privileged Gateway Intents', enable 'Message Content Intent'"
echo "  6. Go to 'OAuth2' in the sidebar"
echo "  7. Under 'OAuth2 URL Generator', check 'bot' scope"
echo "  8. Under 'Bot Permissions', check 'Send Messages' and 'Read Message History'"
echo "  9. Copy the generated URL, open it, and invite the bot to any server you're in"
echo " 10. To get your User ID: open Discord settings > Advanced > enable Developer Mode"
echo "     Then right-click your name anywhere and click 'Copy User ID'"
echo ""

read -rp "Discord Bot Token: " DISCORD_BOT_TOKEN
read -rp "Your Discord User ID: " DISCORD_USER_ID
echo ""

# Optional settings
read -rp "Reply timeout in seconds [120]: " REPLY_TIMEOUT
REPLY_TIMEOUT="${REPLY_TIMEOUT:-120}"

read -rp "Poll interval in seconds [3]: " REPLY_POLL_INTERVAL
REPLY_POLL_INTERVAL="${REPLY_POLL_INTERVAL:-3}"

# Verify the bot token works
echo ""
echo "Verifying bot token..."
BOT_INFO=$(curl -sf "${DISCORD_API:-https://discord.com/api/v10}/users/@me" \
  -H "Authorization: Bot ${DISCORD_BOT_TOKEN}" 2>/dev/null || echo "")

if [ -z "$BOT_INFO" ] || echo "$BOT_INFO" | jq -e '.message' > /dev/null 2>&1; then
  echo "Warning: Could not verify bot token. Double-check it's correct." >&2
else
  BOT_NAME=$(echo "$BOT_INFO" | jq -r '.username // "unknown"')
  echo "Verified! Bot name: ${BOT_NAME}"
fi

# Verify DM channel can be opened
echo "Verifying DM access..."
DM_CHECK=$(curl -sf -X POST "https://discord.com/api/v10/users/@me/channels" \
  -H "Authorization: Bot ${DISCORD_BOT_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "{\"recipient_id\": \"${DISCORD_USER_ID}\"}" 2>/dev/null || echo "")

if [ -z "$DM_CHECK" ] || echo "$DM_CHECK" | jq -e '.message' > /dev/null 2>&1; then
  echo "Warning: Could not open DM channel. Make sure you and the bot share a server." >&2
else
  echo "DM channel verified!"
fi

# Save config
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<EOF
# claude-approve config
# Generated by install.sh — edit freely

DISCORD_BOT_TOKEN="${DISCORD_BOT_TOKEN}"
DISCORD_USER_ID="${DISCORD_USER_ID}"
REPLY_TIMEOUT="${REPLY_TIMEOUT}"
REPLY_POLL_INTERVAL="${REPLY_POLL_INTERVAL}"
EOF

chmod 600 "$CONFIG_FILE"
echo ""
echo "Config saved to $CONFIG_FILE"

# Make hook scripts executable
chmod +x "$SCRIPT_DIR/hooks/on-permission-request.sh"
chmod +x "$SCRIPT_DIR/hooks/on-notify.sh"

# Add hooks to Claude Code settings
mkdir -p "$(dirname "$SETTINGS_FILE")"

if [ ! -f "$SETTINGS_FILE" ]; then
  echo '{}' > "$SETTINGS_FILE"
fi

# Build the hook entries with absolute paths
HOOKS_JSON=$(cat <<EOF
{
  "PermissionRequest": [
    {
      "hooks": [
        {
          "type": "command",
          "command": "${SCRIPT_DIR}/hooks/on-permission-request.sh"
        }
      ]
    }
  ],
  "Notification": [
    {
      "matcher": "idle_prompt",
      "hooks": [
        {
          "type": "command",
          "command": "${SCRIPT_DIR}/hooks/on-notify.sh",
          "async": true,
          "timeout": 10
        }
      ]
    }
  ]
}
EOF
)

# Merge hooks into existing settings (preserving other settings and hooks)
UPDATED=$(jq --argjson hooks "$HOOKS_JSON" '
  .hooks = ((.hooks // {}) * $hooks)
' "$SETTINGS_FILE")

echo "$UPDATED" > "$SETTINGS_FILE"
echo "Hooks added to $SETTINGS_FILE"

echo ""
echo "=== Setup complete! ==="
echo ""
echo "How it works:"
echo "  - When Claude needs permission, you'll get a Discord DM from your bot."
echo "  - Reply Y to allow, N (or anything else) to deny."
echo "  - If you don't reply within ${REPLY_TIMEOUT}s, it denies by default."
echo "  - You'll also get a DM when Claude is idle and waiting for input."
echo ""
echo "To test:"
echo "  echo '{\"tool_name\":\"Bash\",\"tool_input\":{\"command\":\"echo hello\"}}' | ${SCRIPT_DIR}/hooks/on-permission-request.sh"
echo ""
echo "To uninstall: ./uninstall.sh"
