#!/usr/bin/env bash
set -euo pipefail

# claude-sms-approve installer
# Sets up Twilio config and adds hooks to Claude Code settings.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="$HOME/.config/claude-sms"
CONFIG_FILE="$CONFIG_DIR/config"
SETTINGS_FILE="$HOME/.claude/settings.json"

echo "=== claude-sms-approve setup ==="
echo ""

# Check dependencies
for cmd in jq curl; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "Error: '$cmd' is required but not installed." >&2
    echo "  brew install $cmd  (macOS)" >&2
    echo "  apt install $cmd   (Linux)" >&2
    exit 1
  fi
done

# Collect Twilio config
echo "You'll need a Twilio account. Sign up at https://www.twilio.com/try-twilio"
echo "Then get a phone number from the Twilio console."
echo ""

read -rp "Twilio Account SID: " TWILIO_ACCOUNT_SID
read -rp "Twilio Auth Token: " TWILIO_AUTH_TOKEN
read -rp "Twilio Phone Number (e.g. +15551234567): " TWILIO_PHONE_NUMBER
read -rp "Your Phone Number (e.g. +15559876543): " YOUR_PHONE_NUMBER
echo ""

# Optional settings
read -rp "SMS reply timeout in seconds [120]: " SMS_TIMEOUT
SMS_TIMEOUT="${SMS_TIMEOUT:-120}"

read -rp "Poll interval in seconds [3]: " SMS_POLL_INTERVAL
SMS_POLL_INTERVAL="${SMS_POLL_INTERVAL:-3}"

# Save config
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<EOF
# claude-sms-approve config
# Generated by install.sh — edit freely

TWILIO_ACCOUNT_SID="${TWILIO_ACCOUNT_SID}"
TWILIO_AUTH_TOKEN="${TWILIO_AUTH_TOKEN}"
TWILIO_PHONE_NUMBER="${TWILIO_PHONE_NUMBER}"
YOUR_PHONE_NUMBER="${YOUR_PHONE_NUMBER}"
SMS_TIMEOUT="${SMS_TIMEOUT}"
SMS_POLL_INTERVAL="${SMS_POLL_INTERVAL}"
EOF

chmod 600 "$CONFIG_FILE"
echo "Config saved to $CONFIG_FILE"

# Make hook scripts executable
chmod +x "$SCRIPT_DIR/hooks/on-permission-request.sh"
chmod +x "$SCRIPT_DIR/hooks/on-notify.sh"

# Add hooks to Claude Code settings
mkdir -p "$(dirname "$SETTINGS_FILE")"

if [ ! -f "$SETTINGS_FILE" ]; then
  echo '{}' > "$SETTINGS_FILE"
fi

# Build the hook entries with absolute paths
HOOKS_JSON=$(cat <<EOF
{
  "PermissionRequest": [
    {
      "hooks": [
        {
          "type": "command",
          "command": "${SCRIPT_DIR}/hooks/on-permission-request.sh"
        }
      ]
    }
  ],
  "Notification": [
    {
      "matcher": "idle_prompt",
      "hooks": [
        {
          "type": "command",
          "command": "${SCRIPT_DIR}/hooks/on-notify.sh",
          "async": true,
          "timeout": 10
        }
      ]
    }
  ]
}
EOF
)

# Merge hooks into existing settings (preserving other settings and hooks)
UPDATED=$(jq --argjson hooks "$HOOKS_JSON" '
  .hooks = ((.hooks // {}) * $hooks)
' "$SETTINGS_FILE")

echo "$UPDATED" > "$SETTINGS_FILE"
echo "Hooks added to $SETTINGS_FILE"

echo ""
echo "=== Setup complete! ==="
echo ""
echo "How it works:"
echo "  - When Claude needs permission, you'll get a text."
echo "  - Reply Y to allow, N (or anything else) to deny."
echo "  - If you don't reply within ${SMS_TIMEOUT}s, it denies by default."
echo "  - You'll also get a text when Claude is idle and waiting for input."
echo ""
echo "To test: run Claude Code and trigger a permission prompt."
echo "To uninstall: run ./uninstall.sh"
